### ISSUE TITLE
Allow for multiple dictionaries

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#129]
To sort the issue of multiple parties using the same signbank, implement a feature where you can create multiple dictionaries in one instance of signbank.

* Users should have an organisation added, so that the default behavior is to show them their own dictionary. For privacy reasons it should be possible to make dictionary private so that only members of that organisation can view and edit it.
* It should be possible to choose which dictionary is in use, this information should be shown on the base template.
* *Should we allow searches on multiple dictionaries at once?*

**Comment by henrinie** [comment]
One possible solution could be to create a ForeignKey to a new model that specifies different datasets.
Because idgloss should be unique and there would be multiple datasets in one table,  [unique_together](https://docs.djangoproject.com/en/1.8/ref/models/options/#unique-together) with idgloss and this ForeignKey should be used.

**Comment by stevecassidy** [comment]
Would you want to share a Gloss between more than one dictionary? Either way henrinie's suggestion would work - similar to the way that language works now (in fact language might be almost what is needed - or would a dictionary have more than one language?).

**Comment by henrinie** [comment]
@stevecassidy thanks for your insight, you are right about Language, it is almost the same. The requirement is to have multiple (two) separate dictionaries of the same language (FinSL). These dictionaries should be kept separate because they have been created with different annotation conventions. Because of this I think that we might not want to share a Gloss between them.

**Comment by henrinie** [comment]
To tackle the public/private issue, we might need a BooleanField for this.

**Comment by henrinie** [comment]
This will probably be the solution to the issue, unless I can figure out something that is wrong with this.

```
Gloss:
  dataset = ForeignKey(Dataset)
  Meta:
    unique_together = (("idgloss", "dataset"),)

Dataset:
  name = CharField(unique=True, blank=False, null=False)
  is_public = BooleanField(default=False)
```

**Comment by henrinie** [comment]
@ocrasborn & @Woseseltops What do you think of the solution I have described above?
I also have a few questions about Languages in Signbank.

Do you have a requirement (in NGT) for one set of data to include multiple different languages? It seems to me that in NGT Signbank one gloss can be part of multiple languages. Is there a reason why it is implemented in this way (or is it unchanged from Auslan Signbank)?
If you would want to add several languages into NGT (or current FinSL) Signbank, there would be an issue with the reserved gloss names for glosses that share the name between (written) languages. This means that you would have to name glosses differently in different languages even if the gloss name would be the same in both (written) languages.

In FinSL Signbank the requirement seems to be that one set of glosses is always of one language (only). The Finnish team wants to work with FinSL and FinSSL. With that in mind we would also like to add another set of glosses for FinSL (two separate dictionaries for FinSL).

I have proposed to the research team that we change the implementation to suit this requirement. We have decided to go with the solution I have suggested above. We would very much appreciate your insight about this @ocrasborn & @Woseseltops

**Comment by Woseseltops** [comment]
Hi @henrinie ! Interesting topic.

> What do you think of the solution I have described above?

A very good one. We were having similar plans to add another language to the NGT-Signbank, and were planning to use the Language field for it (as suggested by @stevecassidy ), but I get why that wouldn't work for you guys. A new model 'Dataset' is a good alternative. 

Some more ideas:
* If it's important to keep datasets private, you could use the permission system in some way
* For users that can view multiple datasets, an option on the search page where you filter on one or more datasets ( I want only signs from dataset A and B, but not from C).

> Is there a reason why it is implemented in this way (or is it unchanged from Auslan Signbank)?

Unchanged indeed, no special requirements.

> we will enforce that the pair of 'gloss' and 'dataset' are unique

Excellent solution, I can't think of anything to add. This is what you mean by `unique_together = (("idgloss", "dataset"),)` right?

@ocrasborn , this is also an interesting thread for you!

**Comment by stevecassidy** [comment]
So is it the case that one Dataset can contain signs in multiple Languages? If you are going to keep the Language field and add the Dataset field then that would be possible, but I read your description as implying that one Dataset will contain one Language - if that’s the case then why not just extend the Language model to do what you need?

If you do want many languages per dataset then what you propose is fine.

Steve
—
Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy

On 16 Apr 2016, at 1:22 AM, Wessel Stoop <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @henrinie<https://github.com/henrinie> ! Interesting topic.

What do you think of the solution I have described above?

A very good one. We were having similar plans to add another language to the NGT-Signbank, and were planning to use the Language field for it (as suggested by @stevecassidy<https://github.com/stevecassidy> ), but I get why that wouldn't work for you guys. A new model 'Dataset' is a good alternative.

Some more ideas:

  *   If it's important to keep datasets private, you could use the permission system in some way
  *   For users that can view multiple datasets, an option on the search page where you filter on one or more datasets ( I want only signs from dataset A and B, but not from C).

Is there a reason why it is implemented in this way (or is it unchanged from Auslan Signbank)?

Unchanged indeed, no special requirements.

we will enforce that the pair of 'gloss' and 'dataset' are unique

Excellent solution, I can't think of anything to add. This is what you mean by unique_together = (("idgloss", "dataset"),) right?

@ocrasborn<https://github.com/ocrasborn> , this is also an interesting thread for you!

**Comment by henrinie** [comment]
Thanks for your comments @Woseseltops we really appreciate them!
> > we will enforce that the pair of 'gloss' and 'dataset' are unique

> Excellent solution, I can't think of anything to add. This is what you mean by unique_together = (("idgloss", "dataset"),) right?

Yes, that is what it means.

@stevecassidy once again you provided us with some very good points, thank you!
> So is it the case that one Dataset can contain signs in multiple Languages?

One Dataset should contain only one language.

> If you are going to keep the Language field and add the Dataset field then that would be possible, but I read your description as implying that one Dataset will contain one Language - if that’s the case then why not just extend the Language model to do what you need?

I was thinking about extending the Language model, but I would like to keep things semantically correct. Language model would represent languages and Dataset model would represend datasets, I think it is easier to understand their meaning this way.

> If you do want many languages per dataset then what you propose is fine.

I am (probably) going to change the Language model implementation (it is part of the suggestion above).
Glosses would have a ForeignKey to Dataset, not to a Language like they currently do. A Dataset would have a ForeignKey to Language. This would mean that Glosses itself aren't tagged to any languages, only the Dataset they are part of would have the language defined.
The chances are that there will be only a few languages in FinSL Signbank, so we could potentially remove the Language model and have it as a field in Dataset. The Language model might be useful in the future, it certainly would be easier to keep track of relations with having the Language model.

**Comment by henrinie** [comment]
@juzza81 & @oukapipp have a look at this issue.

**Comment by henrinie** [comment]
Changes are now live on the production server.
For those that are interested see commits 4f31ea7 and 2dc1222 for more details.

I will keep this issue open for now, we can use this to discuss the problems we encounter with this implementation.

**Comment by henrinie** [comment]
This feature has been running on production for a while. Further improvements should be handled in other issues. Closing.
