### ISSUE TITLE
Change search template row coloring

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#133]
Green: Gloss is locked
Yellow: Gloss has a video but is not locked yet
Red: Gloss has no video

**Comment by ocrasborn** [comment]
What does 'locked' mean, Henri?

**Comment by henrinie** [comment]
@ocrasborn 'locked' means that the Gloss is locked from editing, so that it is not possible to edit any information the Gloss contains while it is in a 'locked' state. It is supposed to represent that the Gloss is somewhat ready (has everything filled in).
