### ISSUE TITLE
Change translation and keyword implementation

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#134]
Remove the duplicate models. Include both/all/multiple languages in the same model.

**Comment by ocrasborn** [comment]
@Woseseltops , is this applicable to us as well?

**Comment by henrinie** [comment]
@ocrasborn This has to do only with us, not related to your code.

**Comment by ocrasborn** [comment]
@henrinie , @Woseseltops : but that's what we need as well, English translation equivalents. If there's not already an issue for this, I'll create one now.

**Comment by ocrasborn** [comment]
https://github.com/Signbank/NGT-signbank/issues/130

**Comment by henrinie** [comment]
See 2d5aca7 
When fixing this issue, we need to modify the way we show translation equivalents according to chosen language

**Comment by henrinie** [comment]
To make handling translation equivalents more dynamic within signbank, we need some field somewhere to indicate which languages translations equivalents we have or want to show.
At the moment Translation has a foreignkey to Language, we could for example add a boolean field to Language which would indicate if we use that language in translations.

Anyway, if we implement this in some way, the users could decide which languages translations will be shown on gloss_detail page.

**Comment by henrinie** [comment]
I have been **experimenting** with modified models to see how we can improve the implementation of Translations. _(These changes are in the planning phase and might not be implemented)._

I have added models and also added fields in existing models.
We now have roughly the following relations (trying to show only the relevant parts):
```
class Dataset(models.Model):
    """A dataset, can be public/private and can be of only one SignLanguage"""
    name = models.CharField(unique=True, blank=False, null=False, max_length=60)
    is_public = models.BooleanField(default=False, help_text="Is this dataset is public or private?")
    signlanguage = models.ForeignKey("SignLanguage")
    translation_languages =  models.ManyToManyField("Language", help_text="These languages are shown as options"
                                                                          "for translation equivalents.")
    description = models.TextField()

class Translation(models.Model):
    """A translation equivalent of a sign in selected language."""
    gloss = models.ForeignKey("Gloss")
    language = models.ForeignKey("Language")
    keyword = models.ForeignKey("Keyword")

class Keyword(models.Model):
    """A keyword that stores the text for translation(s)"""
    text = models.CharField(max_length=100, unique=True)

class Language(models.Model):
    """A written language, used for translations in written languages."""
    name = models.CharField(max_length=50)
    language_code_2char = models.CharField(unique=False, blank=False, null=False, max_length=2, help_text=_(
        """ISO 639-1 language code (2 characters long) of a written language."""))
    description = models.TextField()
    language_code_3char = models.CharField(unique=False, blank=False, null=False, max_length=3, help_text=_(
        """ISO 639-3 language code (3 characters long) of a written language."""))

class SignLanguage(models.Model):
    """A sign language."""
    name = models.CharField(max_length=50)
    language_code_3char = models.CharField(unique=False, blank=False, null=False, max_length=3, help_text=_(
        """ISO 639-3 language code (3 characters long) of a sign language."""))

```
I have added SignLanguage as a model to represent signed languages.
Language now represents written languages. They are in separate classes because abstracting them in a useful way would pretty much require yet another (base)class.
A vital part of this implementation are language_code's. 2char long language code is used with translation equivalents to match django's get_language() (in search page: to show translations in users selected language [if available]), 3char long language codes could be used with ELAN exports.

**The reasons behind these changes:**
- To make translations (equivalents) dynamic, so that managing translation languages can be done in Signbank.
    - Translation languages can be set for each Dataset, glosses of that dataset will show translation equivalents of the set languages in the Gloss page.
        - For example one dataset could have translations (equivalents) in one language, and another dataset could have translations in 4 different languages.
- In search results: To be able to show Translation equivalents according to users chosen language, if they don't exist in that language, English translations should be shown instead.

I have gotten these features to work, but there might be some pitfalls that I am not thinking of.
Therefore I would be glad to have some feedback on these ideas, if any of you @juzza81 @ocrasborn @Woseseltops @ErwinKomen have any ideas, please share them.

On top of this I am also in the process of planning to make direct translations of glosses (idgloss). If I get this working, we can then get rid of the idgloss_en (idgloss in english) field. Then we could set _direct (official) translations_ of the glosses in any language. These translated glosses could then be used in ELAN when working with different languages in the interface.

**Comment by henrinie** [comment]
Now translations can be added to any language defined in Signbank. The feature is runnin in production, closing this issue.
