### ISSUE TITLE
What information to show on the search page

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#141]
Currently we are showing:
* Gloss name
* Comments
* Translations
* Tags

**Comment by henrinie** [comment]
Hey @juzza81 @jajokera @oukapipp and @hetusyrj , could you tell me what do you want to be shown on the search page?
Voitte vastata myös suomeksi! Eli mitä tietoa haluatte hakusivulla näkyvän?

**Comment by juzza81** [comment]
Hey!

Earlier Jarkko suggested that both glosses in Finnish and English would seem on the search page. Maybe also both translation ones. Henri explained earlier that can choose which language (Finnish or English) wanna use in Signbank but do we need both languages are seen similarly during search process? I would wanna test both languages usage together.

So:

Gloss name (In Finnish and English)
Comments
Translations (both ones, too) => depends if there is still space on search page
Tags

**Comment by henrinie** [comment]
@juzza81 Thanks for the reply!
At some point someone suggested that we would show gloss creation or modified date. If we want to add that, I think we need to remove something else.
@jajokera & @hetusyrj What's your opinion?

**Comment by henrinie** [comment]
We are now showing Gloss in English on the search page.

**Comment by henrinie** [comment]
This discussion is pretty much over now. 
Showing in search results:
* dataset
* gloss
* gloss in english
* translation equivalents
* comments
* tags

With the feature of showing translation equivalents according to chosen language.
Closing.
