### ISSUE TITLE
When editing translation equivalents, unnecessary spaces are added in front of the words

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#145]

**Comment by ocrasborn** [comment]
@Woseseltops , I don't recognise this for our system, but can you double-check?

**Comment by Woseseltops** [comment]
@ocrasborn , checked some things but I don't think we have it, no

**Comment by henrinie** [comment]
This is a more accurate description of the problem.
![finslsb-keywordsissue](https://cloud.githubusercontent.com/assets/14230626/13546660/f07a1558-e2bc-11e5-9235-dfec18ce5fee.png)

**Comment by henrinie** [comment]
It seems that this is caused by copy-pasting text. I can't reproduce this issue with a new gloss.

**Comment by henrinie** [comment]
And now I was able to reproduce this issue.. It seems rather weird, if I remove the spaces, they reappear when I reload the page and edit the field again.

**Comment by henrinie** [comment]
Well now I found the reason, it is a rather stupid one. Automatic formatting of the template file by my editor, believe it or not, added lots of spaces in from of and behind the td-elements. That's what you get for trying to follow PEP8.
