### ISSUE TITLE
Which version of Elan suits for Signbank?

### ISSUE THREAD

**Issue by juzza81** [Signbank/FinSL-signbank#154]
I´m curious which version of Elan do you others use nowadays for annotation between Signbank and Elan? We tried a version 4.6.2 and it didn't work. We consider to upload the newest version (4.9.3) but I have heard that it has some setting dilemmas during annotation.

Your experiences? Thanks.

**Comment by henrinie** [comment]
@juzza81 I would say that use the latest version, if you can get it to work.
It seems though that there are some problems with Mac OS X and ELAN, at least according to [https://tla.mpi.nl/tools/tla-tools/elan/release-notes/](https://tla.mpi.nl/tools/tla-tools/elan/release-notes/) Under **February 03, 2016: Beta version for Mac OS X with JavaFX player**, apparently there is a *BETA version* for a new implementation for Mac OS X.

The 4.6 version of ELAN seems to be 3 years old. I don't like the idea of making Signbank work specifically with an older outdated version. After reading the link above, I wonder if it is possible to update Mac OS X's java version from 1.6 to 1.8 (latest java), and fix the issues that way.

@ocrasborn might have better knowledge about this topic.

**Comment by ocrasborn** [comment]
The ECV function in ELAN has been revised over the years, 4.6 may not offer enough support, and I would recommend upgrading to 4.9.2 or higher.
We're currently working on a script that keeps folders of EAFs in sync with the ECV; hopefully available within a few months in a future release (not 4.9.4 yet, but hopefully the one after).

**Comment by juzza81** [comment]
Thanks for information and sharing your experiences! So we should upload a version of ELAN 4.9.2 or 4.9.3 and then to test how ECV function between ELAN and Signbark practically works.

**Comment by henrinie** [comment]
ELAN released a new version 4.9.4 about a week ago.
Changes can be found in here: https://tla.mpi.nl/tools/tla-tools/elan/release-notes/

I suggest that you upgrade to the newest version @juzza81 @oukapipp

**Comment by ocrasborn** [comment]
Would be my recommendation as well. Check out the Tier Sets function (screencast showing what it does is in the making). Only problems we currently have with ELAN is in Windows 10, which doesn't play back video if there's more than one video attached.

**Comment by juzza81** [comment]
Thanks for this information. We will test the newest Elan version within Signbank and we still use an old version (4.6.2.) for annotation process. Until our annotation process will have accomplished its current aim, we will transfer to use more Signbank and Elan (the newest version) together.

**Comment by henrinie** [comment]
Closing this issue, I guess it has been "solved".
