### ISSUE TITLE
Multiple videos per gloss page

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#164]
Add a possibility to add multiple videos for one Gloss page.
Because of this, we should change the way we store video files, at least the file naming should be implemented differently.

**Requirements:**
- Every video should have a 'description' to tell what the video is about
    - It is easier to figure out what each video is for when there are multiple videos on a gloss page
    - Videos should be separated from each others and this 'description' should be shown either on top or bottom of the video box.
- (Not a priority) It should be possible to prioritise the videos so that the order of the videos can be arranged.

**Comment by ocrasborn** [comment]
We now have a panel Other Media, where both videos and images can be linked. Is that what you mean? They are presently not displayed anywhere in the interface, but can be downloaded by users.

**Comment by henrinie** [comment]
Not exactly like you described.
The requirement seems to be that it should be possible to upload multiple videos on one gloss page, and all of those videos should be shown.
So we will probably make the gloss page show all the videos that are related to a particular gloss. They should be responsive so that with smaller screen sizes the videos would be stacked when multiple don't fit to the space horizontally.

**Comment by henrinie** [comment]
Added a new requirement:

- Every video should have a 'description' to tell what the video is about
    - It is easier to figure out what each video is for when there are multiple videos on a gloss page
    - Videos should be separated from each others and this 'description' should be shown either on top or bottom of the video box.

**Comment by juzza81** [comment]
Fine job Henri and it is now more handful to add and separate several videos on a gloss page.

**Comment by henrinie** [comment]
Closing this issue because it has been solved. Moved sub-issues to be separate issues.
