### ISSUE TITLE
Still image to gloss page

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#165]
Add a possibility to add still image(s) to gloss page

**Comment by ocrasborn** [comment]
This was recently added to NGT SB, you'll easily find the issue.

**Comment by henrinie** [comment]
I'll have a look, thank you @ocrasborn

**Comment by henrinie** [comment]
Still images might not be needed, we can supply the needed pictures in the videos metadata, and then load only the metadata for the videofiles in order to show the picture included in metadata.

**Comment by henrinie** [comment]
I can't find a way to add the image to the videos metadata in a way that could be useful.
Seems like there are two options:
1. Use 'poster' attribute inside video tag (needs an image file)
2. Make the video start in the middle, not sure how easy it is to calculate the middle point from a video. (We could also just define that the videos will start from 00:02).

Both of these methods need that the video tag is set to load metadata.

**Comment by henrinie** [comment]
@juzza81 & @oukapipp 
I need your opinion on this:

1. We wanted to have still images on the gloss page, but we also want to have multiple videos on a gloss page. Do we also want to have multiple still images?

2. We could do without adding (separate) still images to the gloss page, I have figured out two ways that would make it possible:
    * Load the videos from their middle point or from some other position like +2 seconds. This would show that positions picture from the video, but it would also start playing the video from that point too (might not be convenient if you want to see the video from the beginning).
    * Add still images and show them as the videos poster images. We can add still images to the site and show them "in the place of the video" (under the play button), once the user begins watching the video, the poster images will not be shown any more. These images could be uploaded manualle, or we could catch them from the videos automatically (the results might vary though).

**The same in Finnish:**

1. Tarvitsemmeko jokaisesta videosta still kuvan?

2. Sen sijaan että lisäisimme glossisivulle still kuvia, voisimme näyttää kuvat videoruudussa:
    * Voisimme aloittaa videot keskikohdasta tai jostain muusta kohdasta, esimerkiksi +2 sekuntia. Tämä näyttäisi videon kuvana valitun kohdan, mutta se myös aloittaisi videon näyttämisen kyseisestä kohdasta.
    * Videoihin voidaan lisätä poster kuvat, nämä kuvat näytetään aina ennenkuin video laitetaan pyörimään. Näitä kuvia voisi sitten lisätä sivulta, tai ne voitaisiin vaikka kaapata automaattisesti suoraan videoista palvelimella (se olisi hieman arpapeliä sen suhteen että videosta saisi aina oikean kohdan).

**Comment by juzza81** [comment]
Hey all!

Good question from Henri. It is hard to say which form would be the most suitable for making a still image about the gloss. I have checked how there has been made in Signbank of BSL (http://bslsignbank.ucl.ac.uk/dictionary/) and Auslan (http://www.auslan.org.au/dictionary/). Not still images. I dont know how in Netherlands?

Moreover, there can be found two-styled still images from pubished national dictionaries in Finland:

- Suvi: http://suvi.viittomat.net/wordsearch.php?a_id=406&word_search=auto&offset=0&sssf=0&mpw=1

- Signwiki: http://finsl.signwiki.org/index.php/Facebook

You can see that in Suvi there has been created exact arrows when it is easier to identify which sign there is concerned. Instead, there has been used a catched video image version in Signwiki but it is more hard to get clear about the image until finally see a video. Henri, your suggestion can be seen in a near relationship with Signwiki´s one. I suppose that FAD (Kuurojen Liitto) will aim a same style as in Suvi. 

My personal opionion: a catched video image version is just a lottery game as Henri has mentioned. It is often difficult to find a right spot from the video and moreover a sign may include several structural parts when it is impossible to present it perfectly within a still image. Therefore there is needed arrows for support but who/how will make them?

My suggestion:
During August (many of us back at work till middle of August) we must have a meeting and discuss together about this very important topic.

**Comment by henrinie** [comment]
@juzza81 We need to discuss about this in the next meeting.
I think that we should just start with captured images (either be user or by Signbank) from the videos. The arrows can then later be edited in those pictures if needed.

I think that there are three ways we can get the still images from the videos:
1. *Randomly* take a screen capture from the video (for example in the middlepoint of every video), handled on the server by Signbank.
2. The user takes a screen capture from the video and uploads it to Signbank.
3. The user selects a desired frame from the video in Signbank, then Signbank captures that frame as the still image of the video. This option would require the most work, and it is hard to predict how easy it would be to select the correct frame from the video.

**Comment by ocrasborn** [comment]
@juzza81 We've started experimenting with the middle frame of every video file, which turns out to be very usable as a cheap guess. Even if it does not display the sign in the style of printed dictionaries, with arrows or edited images showing the movement, it provides a lot of information to help distinguish variants from each other. You can typically see whether it's 1h/symmetrical/asymmetrical, what the location is, and often what the handshape is. We've exported all frames from each video, and we might for some signs manually select the optimal frame, but won't go as far as to add arrows, edit images, etc.
We're currently displaying them in mini-view on the left in the list search results, and at the same size as the video in the detail view.

**Comment by henrinie** [comment]
It was rather easy to implement the frame capture from the video of **option 3.**
So option 3. should be totally doable.
Since we can have multiple videos on a gloss page, we need to have a button or something else for each of the videos (perhaps a dropdown menu where you can choose which videos frame to capture).
This way the Signbank users can take the screenshots from the desired point of the video, and then (when and if implemented) upload them to Signbank as the poster image of the video.
A poster image is shown in the place of the video before the video is loaded, we don't necessarily need another

**Comment by henrinie** [comment]
Adding still images to glossvideos is now possible by capturing a screenshot of the desired frame of each glossvideo. 
Users can do this on the gloss_detail page for each video that has been uploaded for that gloss.

1. User must enable edit from the enable edit button.
2. User must then select the desired frame from the video.
3. User must then press the button 'Capture new poster image' (this button will appear when edit mode is enabled)
4. Then a modal window will show the captured frame from the video.
5. User can choose to save the captured frame as the poster image, or cancel.

@juzza81 @oukapipp Leaving this open for a little while if someone wants to give feedback/finds errors.

**Comment by henrinie** [comment]
New issue #199 has to do with this one, the capture poster image button does not seem to show on Mac+Chrome combination, other combinations of windows+linux/firefox+chrome seem to work.
