### ISSUE TITLE
Show Glosses Dataset in search results and in gloss page

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#168]
When searching within multiple Datasets it might be useful to show which Dataset each Gloss is part of.
This would be especially important on the Gloss page.
Figure out a good way to indicate Dataset for both search results and gloss page.

**Comment by juzza81** [comment]
Waiting with enthusiasm which results there are coming.

**Comment by henrinie** [comment]
#178 was fixed already. So is this.
