### ISSUE TITLE
LANG_DEF for Finnish (iso CDB)?

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#170]
NGT Signbank has defined (for ELAN) some languages like this:
`
<LANGUAGE LANG_DEF="http://cdb.iso.org/lg/CDB-00138502-001" LANG_ID="eng" LANG_LABEL="English (eng)"/><LANGUAGE LANG_DEF="http://cdb.iso.org/lg/CDB-00138580-001" LANG_ID="nld" LANG_LABEL="Dutch (nld)"/>
`

What are those CDB links and how can I find out which one to use for Finnish? The links don't work (for me at least). On top of that I can't find any information about them anywhere.
@juzza81 Do you have any idea? @ocrasborn Perhaps you can explain these?

**Comment by henrinie** [comment]
@ocrasborn What are these links? 
> http://cdb.iso.org/lg/CDB-00138580-001

Do you know where I could find the corresponding one to Finnish? (The links don't work and I have no idea what "system" or standard they are part of, or if they are necessary at all?).

I tried to add the English LANG_DEF according to how you have defined it, and for Finnish I used "undefined (und)". Then I tried that ECV in ELAN, but the ecv didn't seem to show multiple languages. It is possible that I don't know how to use them correctly, because I have never actually used ELAN before.

**Comment by ocrasborn** [comment]
Don't recognise this iso-link before, I thought the references were predictable on the basis of the three-letter ISO language codes. Perhaps better work from ELAN, try to define languages in an EAF document, and see how it looks.

**Comment by henrinie** [comment]
So ELAN has some kind of language settings under
`Edit -> Edit List of Languages`
I was able to extract the ISO link for Finnish:
`Finnish (fin) - fin - http://cdb.iso.org/lg/CDB-00138509-001`
Thanks for the tip @ocrasborn 

What I don't know is what these languages represent, is it the written language that you write the annotations with, or is it the language that is in the videos?
Anyways for future reference I will store some languages ISO links here:
`Finnish (fin) - fin - http://cdb.iso.org/lg/CDB-00138509-001`
`Finnish Sign Language (fse) - fse - http://cdb.iso.org/lg/CDB-00135119-001`
`Finland-Swedish Sign Language (fss) - fss - http://cdb.iso.org/lg/CDB-00135117-001`
`English (eng) - eng - http://cdb.iso.org/lg/CDB-00138502-001`

**Comment by ocrasborn** [comment]
ELAN uses the languages as the "annotation content languages", so the language of the annotation text. The language used in the related media that the annotation describes is not encoded anywhere in ELAN, but somewhere in the metadata of the media file(s). Point for improvement, I'd say.
(It is convenient though, this content language, we use it to be able to export a Dutch-English ECV from Signbank, then switch annotation content language in the Options menu.

**Comment by henrinie** [comment]
Thanks for your comments, you have been a huge help.

@juzza81 
I tested this just how Onno suggested, all you need to do to change the annotation language is to select the desired language from:
`Options -> Language for multilingual content`

**Comment by henrinie** [comment]
http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/components/clarin.eu:cr1:c_1271859438110
