### ISSUE TITLE
Add sorting to 'Glosses in English' on the search page

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#176]

**Comment by ocrasborn** [comment]
Would this help? https://github.com/Signbank/NGT-signbank/issues/143

**Comment by henrinie** [comment]
It might help, I have done sorting for 'Glosses' already, this issue is more like a reminder to do this to the English Glosses too.
I will check out the work of @ErwinKomen.

**Comment by henrinie** [comment]
r
