### ISSUE TITLE
User rights control for Datasets

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#180]
Find a way to determine how we can have control who can see and edit different Datasets (Create some way to control which Datasets the users can work with).

Something like django-guardian could be used to solve this:
http://django-guardian.readthedocs.io/en/stable/userguide/assign.html

**Comment by henrinie** [comment]
This might be more complicated than I first thought, now that we have a public view as well. If we want to limit access to certain objects, based on its dataset, how do we allow everyone to access the public dictionary, the objects are essentially the same.
Django-guardian seems to do work on the model/object level, and this would require different behavior based on the view. Will have to look into this more.

**Comment by henrinie** [comment]
Well hold on, obviously we check the permissions in the view, and only do restrictions in the "admin" views.

**Comment by henrinie** [comment]
This seems pretty straightforward to set up with django-guardian.
Just have to remember all the views that need object level permission checks.
For the users however, I think that setting these object level permissions might be confusing, at least via django-admin.

**Comment by henrinie** [comment]
So I have gotten it working, but the way I am doing it at the moment doesn't seem to be very optimal, because I have to remember to put the restrictions in every place that access glosses, and lists datasets.
It would be useful to be able to edit the form's querysets to limit modelchoicefields for example, but on default modelforms don't have request object, which is needed in order to determine the user of the request.

**Comment by henrinie** [comment]
This is working, closing the issue.

**Comment by susanodd** [comment]
Based on @henrinie's comment above, I checked the CSV export and import for the NGT signbank.
These both restrict import and export to those datasets the user has access to.
https://github.com/Signbank/NGT-signbank/issues/223
