### ISSUE TITLE
Upload multiple video files

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#188]
We need to figure out a way that allows uploading multiple videos at once.
It should be efficient, easy to use and minimize user error.

Each video uploaded should be connected to a Gloss.

Ideas for implementation:
- Upload n+1 videos at once. Show a list of those videos that don't have a foreign key to a Gloss. The user should be able to connect a video to a Gloss.

**Comment by ocrasborn** [comment]
You know about this, do you? --> https://github.com/Signbank/NGT-signbank/wiki/How-to-batch-upload-videos-for-signbank.science.ru.nl

**Comment by henrinie** [comment]
@ocrasborn I know about your batch upload thing, I am not sure if I have seen that wiki though, thank you for reminding!

We looking for a more user friendly way to do this. We lack the infrastructure to implement it like you have, and we also lack a little on the ability side too, most users are not comfortable using command line or ftp programs.
If we can do this within Signbank, there will be no need for more infrastructure and the configuration of it. Then anyone that have FinSL-signbank installed can use this feature without having to do any "voodoo tricks". Well, at least that is the plan.

**Comment by ocrasborn** [comment]
Sounds good to me.

**Comment by henrinie** [comment]
Storing some info here for later use.
We might need to upgrade to django 1.10 to get a proper multiple file upload feature. A very quick look at the docs in 1.10 mentions multiple file upload, 1.8 docs don't.

There are apps that try to make this easier using html5's multiple attribute, for example: https://github.com/Chive/django-multiupload
Some probably useful stackoverflow page: http://stackoverflow.com/questions/5742119/django-form-with-multiple-file-fields/7355997#7355997

**Comment by henrinie** [comment]
The basic features are now done, see commit 09c2d14.
These features have not been tested in a real environment that is hosted outside of localhost.

It should be now possible to upload multiple videos from the website.
There is a feature where you can then easily connect these videos, that don't have a gloss set, to glosses.
