### ISSUE TITLE
Organize permissions

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#197]
Permissions form views are at the moment are not defined in a coherent way.
We need to organize all permissions following the same principles.

**Comment by henrinie** [comment]
This is done for now, we need to continue this later when the codebase has been refactored more.

**Comment by ocrasborn** [comment]
@Woseseltops , is there something useful/safe we could adopt from FinSL here?

**Comment by Woseseltops** [comment]
Not really sure, what would be the advantage @henrinie ?

**Comment by henrinie** [comment]
Perhaps more control over permissions and what users can do and where they can go. Not much more.
