### ISSUE TITLE
Capture videos via webcam

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#212]
Find out if it is viable to implement a feature that would make it possible to capture videos on gloss page (and add gloss page), and at the same time upload them.
This would speed up the annotation process when new glosses are identified/added, as it would be possible to add a video when adding a new gloss.

**Comment by Woseseltops** [comment]
@ocrasborn wow this is a cool idea

**Comment by ocrasborn** [comment]
@Woseseltops , yes, I agree, this would save us a lot of time as well. I'll be creating an issue for it.

**Comment by henrinie** [comment]
This could be a possibility: https://github.com/muaz-khan/RecordRTC 
 I did not get their demo working properly at first, but for some reason after that it worked with Firefox and Chrome on Linux.
This could probably work for what we need it for, but I have not taken a detailed look at it yet.

Their demo is located at:
https://www.webrtc-experiment.com/RecordRTC/

**Comment by henrinie** [comment]
When making this feature possible it seems that **browser compatibility** could be a minor issue. I reckon it is a minor issue because I think it is reasonable to expect the 'advanced users'/admins of Signbank to use a browser that readily supports these features.

The browsers that will most likely work: Firefox, Chrome, (Opera?)
Browsers with basic support (might work): Edge
Browsers that most likely will not work: Safari, Internet Explorer

**Comment by henrinie** [comment]
First test version of this feature works. Only tested on Linux with Firefox & Chrome.
The feature is implemented by using https://github.com/muaz-khan/RecordRTC
It would probably be possible to do it without this dependency, but by continuing using RecordRTC will save a lot of time at this point.

**Comment by henrinie** [comment]
The video files are saved with VP8 codec. They run perfectly fine with my browsers, but when viewed in django admin they do not.
We might need to encode them to h264 on the server.
Or we can live with the fact that these videos are meant to be temporary anyway.

**Comment by ocrasborn** [comment]
Good to hear! I look forward to the user experiences from Finland. In our own workflow, different people want to look at the temporary videos, as they prepare to discuss them in our meetings on whether a proposal for a sign will be accepted or altered or rejected. That implies different platforms and different browsers.

**Comment by henrinie** [comment]
It seems that webm/VP8 is supported by the major browsers. https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats
I got outdated information from somewhere before.

This means that there is not much point to encode these videos to mp4/h264.
So @ocrasborn the videos recorded should show on most browsers and platforms.

On the other hand, I am not so sure about the actual recording feature. I would need someone to test that for me with Safari or Edge for example.

**Comment by henrinie** [comment]
So the first **test** version of the webcam feature is done. Need to put it live so that everyone can test it.
Seems to work with Firefox and Chrome on Linux.
It still needs lots of polishing and fixing. The javascript should probably be moved at the end of the file, and somewhat be minimized. I am using django translations inside the javascript code, dunno if that would be affected.

**Comment by henrinie** [comment]
The first version is live on our server. @juzza81 & @jajokera please test it with different browsers.

**Comment by henrinie** [comment]
**Working os+browser combinations for recording:**

- Mac + Firefox
- Linux + Firefox 45.7.0
- Linux + Chrome 56.0.2924.87
- Linux + Opera 43.0.2442.806

**Not working:**

- Mac + Safari 10.0.03
- Mac + Chrome
- Windows + Internet Explorer

**Working os+browser combinations for viewing webm/vp8 videos:**

- Mac + Firefox
- Linux + Firefox
- Linux + Chome
- Linux + Opera

**Not working:**

- Mac + Safari 10.0.03
- Windows + Internet Explorer

**Comment by henrinie** [comment]
Mac+Chrome 56.0.2924.87 seems to report the following:

> Uncaught TypeError: navigator.mediaDevices.getUserMedia is not a function.

**Comment by henrinie** [comment]
See if this could be added to signbank-video

**Comment by henrinie** [comment]
This seems stable enough to close this issue. Further problems encountered should be their own issues. Closing.
