### ISSUE TITLE
Write tests for dictionary

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#213]
Signbanks dictionary app needs tests.
We should start with unit tests.
Some test have been written already, but the coverage isn't too great yet.

**Comment by stevecassidy** [comment]
A good opportunity to alert you to the work I’m doing at the moment on Auslan SB. I had a student working on modularisation of SB last semester, I’m now finishing off that work and porting things up to Django 1.10.  I have four sub-projects now (dictionary, video and feedback and a theme project)

https://github.com/stevecassidy/signbank-modular
https://github.com/stevecassidy/signbank-dictionary
https://github.com/stevecassidy/signbank-video
https://github.com/stevecassidy/signbank-feedback
https://github.com/stevecassidy/signbank-theme-auslan

this isn’t done yet, I’ve just got things mostly working again under this new structure but the three main projects contain some tests.

Steve

**Comment by henrinie** [comment]
@stevecassidy Thanks for letting us know. I will keep a close eye on your work, I like how you have modularized the application.
I will look at the tests and see if we can use any of them.

**Comment by henrinie** [comment]
I should note that FinSL-signbank runs on django 1.10.
@ocrasborn @Woseseltops You might want to take a look at Steves work too.

**Comment by henrinie** [comment]
This issue is way too generic. We have some tests, but we definitely need more. I would like to do some cleanup before writing more tests though. Closing.
