### ISSUE TITLE
Tweak search features

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#217]
Test different options regarding search (for glosses).
Currently we use case sensitive 'contains', but it is not always the best choice. If you want to search for 'KUU', you get plenty of search results where 'KUU' is included, making it harder to find the actual 'KUU' you were searching for.

One possibility is to make options on the search page where the user could choose the type of search.

**Comment by henrinie** [comment]
Party related:
Managed to reduce the amount of database queries done when searching with 813b83cb10a0b8e54d08dd0013e9e0b1d3c86bc0 and ce58712035913575b8c34305be3fea787894362e

With these optimizations the search page (on production server) currently loads in 4000-5000ms when searching for 3000 glosses with no other filters. This is twice as fast as it used to be (around 11 000ms) after 813b83cb10a0b8e54d08dd0013e9e0b1d3c86bc0, which already reduced the page load time.

I think this is enough optimization for now, even though the search page load time still has some room for improvements.

**Comment by ocrasborn** [comment]
@Woseseltops , is this something that we can profit from?

**Comment by henrinie** [comment]
Doesn't seem very relevant at the moment. Will get back to this if the need arises. Closing.
