### ISSUE TITLE
Webfont for handforms

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#230]
This was requested by Leena. This is a low priority thing at the moment and might not make into the first official release.

Add some webfont that includes 'sign language' handforms(?).
This font would be used to add different kind of 'handform notations(?)' to glosses.

- Find such a webfont that is opensource and can be added in the project.
- Figure out a way for easy input of these fonts.
    - Perhaps a list from which a user can choose from.

**Comment by henrinie** [comment]
Perhaps something like one of these?
https://en.wikipedia.org/wiki/SignWriting
https://en.wikipedia.org/wiki/Si5s
http://www.unicode.org/L2/L2016/16225-signwriting-pres.pdf

**Comment by ocrasborn** [comment]
Perhaps more likely http://www.cslds.org/v3/resources.php?id=1, no? 
Or HamNoSys, https://www.sign-lang.uni-hamburg.de/dgs-korpus/index.php/hamnosys-97.html ?

**Comment by henrinie** [comment]
@ocrasborn Thanks a lot for that!
The first one looks very promising.

Last time I had a look at HamnoSys I did not notice that they had handshapes. Would be nice if they were available as a font, I was unable to find them as a font with a quick search. Only found this:https://www.sign-lang.uni-hamburg.de/dgs-korpus/files/inhalt_pdf/HamNoSys_Handshapes.pdf
They seem to have some fonts available in https://www.sign-lang.uni-hamburg.de/dgs-korpus/files/inhalt_dateien/ham2hpsg23.zip but they do not seem to include the handshapes.

**Comment by ocrasborn** [comment]
The HamNoSys font doesn't include drawings of handshapes, but experts like Leena can no doubt read the symbols to represent handshapes. (I doubt that I can read more than the most frequent ones myself.)

**Comment by henrinie** [comment]
@ocrasborn Good to know.

I am under the impression that these fonts with handshapes would be shown to everyone publicly, therefore a notation system(?) like hamnosys is not really usable.

**Comment by henrinie** [comment]
Not relevant currently.
