### ISSUE TITLE
Deploy the site via HTTPS only?

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#85]
Originally reported by: **Henri Nieminen (Bitbucket: [heilniem](http://bitbucket.org/heilniem), GitHub: [heilniem](http://github.com/heilniem))**

---

Site login page is sent via http and therefore the passwords can be captured.
The site may not be super security critical, but it would still be a good idea to deploy the whole site via https.

---
- Bitbucket: https://bitbucket.org/heilniem/signbank-fi/issue/85

**Comment by henrinie** [comment]
There is one major setback with deploying the whole site via https, which is that ELAN doesn't open https links.

**Comment by henrinie** [comment]
Check if it is viable to run everything reliably over https and have elan exports run over http.

**Comment by Woseseltops** [comment]
FYI: our Signbank runs on HTTPS since August; any HTTP requests are redirected, except for the ELAN export.

**Comment by henrinie** [comment]
@Woseseltops That's great!
FinSL also runs on https, but it is not enforced, because ELAN doesn't support https.
I am planning to do it similarly to yours, I am just afraid of the possible loopholes that might be left unnoticed. It would be easier to enforce all connections to use https and not adding exceptions.

**Comment by henrinie** [comment]
See https://github.com/Signbank/NGT-signbank/wiki/Developer-guide#https-and-java-16- for instructions on how to get https working with ELAN.
Also see this comment: https://github.com/vanlummelhuizen/ASL-ELAN/issues/15#issuecomment-275370369

**Comment by henrinie** [comment]
Some features don't work in all browser without a HTTPS connection, like our video-recording feature #212 
At least Chrome and Opera restrict the usage of getUserMedia() to https connections only. Some other browsers might do the same.

**Comment by henrinie** [comment]
I decided it is finally time to move onto HTTPS only. Allowing ECV links to be served with HTTP, did not want to mess with the certificates to make them to work with ELAN.

Using bunch of django settings to  try to secure the site with https. Most of these settings won't work if using proxies. To send MEDIA and STATIC files with HTTPS, configuration is needed on the web server.

Finally closing this one.
